---
title: "Data Assignment"
author: "Priyasha Chawla and Beryl Nana Ama Akuffo-Kwapong"
date: "17/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

\begin{center}
\Huge{PPOL 670 | Assignment 04}

\Huge{Data Visualization, Markdown, and Git}
\end{center}

\vspace{0.1in}

```{}
library(readxl)
project <- read_excel("Downloads/AIU All Women Dataset.xlsx")

status_women <- project %>%
  mutate_if(is.numeric, round, 2) %>%
  select(country = country, current_married = pct_currentlymarried) %>%
  group_by(country) %>% 
  summarize(sum(current_married)) %>% 
  status_women
  status_women <- melt(status_women,  id.vars = 'country', 'sum(current_married)') %>% 
  status_women
  #mutate(name = fct_reorder(country, value)) %>%
  #mutate(name = fct_reorder(country, current_married)) %>%
  ggplot(status_women, aes(x = country, y = value)) +
    geom_bar(stat="identity", width = 0.3, color = "green", fill = "white") +
    geom_text(aes(label=value), vjust=-0.3, size=2.5) +
    coord_flip() +
    xlab("") +
    theme_bw()+
    scale_x_discrete(limits=c("Ghana", "India", "Morocco", "Niger", "Nigeria", "Mexico")) 
```


```{}
maternal_death <- project %>%
  select(continent = region, cause_abortion = pct_matdeaths_abortions, cause_miscarriage = pct_matdeaths_miscar, cause_ectopic = pct_matdeaths_ectopic, cause_hemor = pct_matdeaths_hem, cause_hypertension = pct_matdeaths_hyptn, cause_otherdirect = pct_matdeaths_other) %>% 
  group_by(continent) %>% 
  summarize(sum(cause_abortion), sum(cause_miscarriage), sum(cause_ectopic), sum(cause_hemor), sum(cause_hypertension), sum(cause_otherdirect))
maternal_death <- melt(maternal_death,  id.vars = 'continent', variable.name = 'series')
maternal_death

ggplot(maternal_death,aes(x = factor(continent), y = value, fill = series) ) +
  geom_bar(stat="identity", position = 'dodge') +
  labs(
      title = "Causes of Maternal Deaths by World Regions",
       subtitle = "Grouped by continents",
       caption = "Source: The Guttmacher Institute", 
       x = "Maternal Death Causes By Regions", y = "Percentage of Death by Each Cause",
  ) +
      scale_fill_discrete(name = "Causes of Maternal Deaths", labels=c("sum(cause_abortion)" ="Abortion", "sum(cause_miscarriage)" = "Miscarriage","sum(cause_ectopic)" = "Ectopic Pregnancy", "sum(cause_hemor)" = "Hemmorrhage", "sum(cause_hypertension)" = "Hypertension","sum(cause_otherdirect)" = "Other Direct Causes"))

```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
