---
title: "Assignment_04"
author: "Priyasha Chawla and Beryl Nana Ama Akuffo-Kwapong"
date: "17/02/2022"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

\begin{center}
\Huge{PPOL 670 | Assignment 04}

\Huge{Data Visualization, Markdown, and Git}
\end{center}

\vspace{0.1in}

```{r}
library(tidyverse)
library(ggplot2)
library(reshape2)
library(forcats)
library(dplyr)
library(plotly)
library(viridis)
library(hrbrthemes)
library(scales)

library(httr)
set_config(config(ssl_verifypeer = 0L))
library(readxl)

project <- read_excel("~/Desktop/Assignment_04/data/AIU All Women Dataset.xlsx")

```


```{r, fig.height = 20}
#Graph 2 - percentage of maternal deaths caused by each cause by region 
graph2 <- project %>%
  mutate_if(is.numeric, round, 2) %>%
  select(continent = region, cause_safeabortion = pct_matdeaths_safeabs, cause_unsafeabortion = pct_matdeaths_unsafeabs, cause_miscarriage = pct_matdeaths_miscar, cause_ectopic = pct_matdeaths_ectopic, cause_hemor = pct_matdeaths_hem, cause_hypertension = pct_matdeaths_hyptn, cause_otherdirect = pct_matdeaths_other, cause_inf = pct_matdeaths_inf, cause_indirect = pct_matdeaths_indirect) %>% 
  group_by(continent) %>% 
  summarize(weighted.mean(cause_safeabortion), 
            weighted.mean(cause_unsafeabortion), 
            weighted.mean(cause_miscarriage), 
            weighted.mean(cause_ectopic), 
            weighted.mean(cause_hemor), 
            weighted.mean(cause_hypertension),
            weighted.mean(cause_otherdirect),
            weighted.mean(cause_inf),
            weighted.mean(cause_indirect))  %>%
  mutate_if(is.numeric, round, 2)
graph2 <- melt(graph2,  id.vars = 'continent', variable.name = 'series')

#Creates a bar graph showing the rates of the various causes of deaths in each region
ggplot(graph2,aes(x = factor(continent), y = value, fill = series) ) +
  geom_bar(stat="identity", position = 'dodge') +
  geom_text(aes(label=value), position=position_dodge(width=0.9), vjust=-0.01) +
  labs(
    title = "Causes of Maternal Deaths In World Regions",
    caption = "Source: The Guttmacher Institute", 
    x = "Maternal Death Causes By Regions", y = "Percentage of Death by Each Cause",
  ) +
  scale_fill_discrete(name = "Causes of Maternal Deaths", 
                      labels= c("weighted.mean(cause_unsafeabortion)" = "Unsafe Abortion", 
                               "weighted.mean(cause_safeabortion)" = "Safe Abortion",
                               "weighted.mean(cause_miscarriage)" = "Miscarriage",
                               "weighted.mean(cause_ectopic)" = "Ectopic Pregnancy", 
                               "weighted.mean(cause_hemor)" = "Hemmorrhage", 
                               "weighted.mean(cause_hypertension)" = "Hypertension",
                               "weighted.mean(cause_otherdirect)" = "Other Direct Causes",
                               "weighted.mean(cause_inf)" = "Maternal Infection",
                               "weighted.mean(cause_indirect)" = "Indirect Causes")) +
  facet_wrap ( ~continent,
               ncol = 1,
               scales = "free",
               drop = TRUE,
               shrink = TRUE,
               as.table = TRUE,
               strip.position = "top")

```

